import { describe, expect, it, vi } from "vitest";
import Database from "better-sqlite3";
import { createDashboardsRoutes } from "../routes/dashboards.js";
import { ensureDashboardTables } from "../../services/dashboard.js";
import type { WebUIServerDeps } from "../types.js";

vi.mock("../../utils/logger.js", () => ({
  createLogger: vi.fn(() => ({
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
    debug: vi.fn(),
  })),
}));

function makeDeps() {
  const db = new Database(":memory:");
  ensureDashboardTables(db);
  return {
    memory: { db },
  } as unknown as WebUIServerDeps;
}

describe("dashboard routes", () => {
  it("lists dashboard profiles, templates, and widget catalog definitions", async () => {
    const app = createDashboardsRoutes(makeDeps());

    const dashboardsRes = await app.request("/");
    const dashboards = await dashboardsRes.json();
    expect(dashboards.data).toHaveLength(1);
    expect(dashboards.data[0].widgets.length).toBeGreaterThan(0);

    const templatesRes = await app.request("/templates");
    const templates = await templatesRes.json();
    expect(templates.data.map((template: { id: string }) => template.id)).toContain("operations");

    const catalogRes = await app.request("/widgets/catalog");
    const catalog = await catalogRes.json();
    expect(catalog.data.map((definition: { id: string }) => definition.id)).toContain(
      "dynamic-table"
    );
  });

  it("creates a profile, adds a generated widget, and exports it", async () => {
    const app = createDashboardsRoutes(makeDeps());

    const createRes = await app.request("/", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        name: "Research",
        description: "Generated research widgets",
        widgets: [],
        layout: { lg: [], md: [] },
      }),
    });
    expect(createRes.status).toBe(201);
    const created = (await createRes.json()).data;

    const widgetRes = await app.request(`/${created.id}/widgets`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        definition: {
          id: "research-notes",
          name: "Research Notes",
          description: "Markdown generated during an agent session",
          category: "content",
          dataSource: { type: "static" },
          renderer: "markdown",
          defaultSize: { w: 6, h: 4 },
          configSchema: { type: "object" },
        },
        title: "Market notes",
        data: "# Notes\nGenerated by the agent.",
        temporary: true,
        sessionId: "session-42",
      }),
    });
    expect(widgetRes.status).toBe(201);
    const widget = (await widgetRes.json()).data;
    expect(widget.definitionId).toBe("research-notes");

    const exportRes = await app.request(`/${created.id}/export`, { method: "POST" });
    const exported = (await exportRes.json()).data;
    expect(exported.dashboard.widgets[0].definitionId).toBe("research-notes");
    expect(exported.definitions[0].id).toBe("research-notes");
  });

  it("imports a dashboard export bundle", async () => {
    const app = createDashboardsRoutes(makeDeps());

    const res = await app.request("/import", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        bundle: {
          version: "1.0",
          exportedAt: "2026-04-24T00:00:00.000Z",
          dashboard: {
            id: "external",
            name: "External",
            description: null,
            widgets: [
              {
                id: "w1",
                definitionId: "dynamic-kpi",
                title: "KPI",
                config: {},
                data: { label: "Open tasks", value: 12 },
                pinned: true,
                temporary: false,
                sessionId: null,
                createdAt: 1,
                updatedAt: 1,
              },
            ],
            layout: { lg: [{ i: "w1", x: 0, y: 0, w: 3, h: 2 }] },
            isDefault: false,
            createdAt: 1,
            updatedAt: 1,
          },
          definitions: [],
        },
        options: { name: "Imported external" },
      }),
    });

    expect(res.status).toBe(201);
    const imported = (await res.json()).data;
    expect(imported.name).toBe("Imported external");
    expect(imported.widgets[0].definitionId).toBe("dynamic-kpi");
  });
});
