import { describe, expect, it, beforeEach } from "vitest";
import Database from "better-sqlite3";
import {
  DashboardStore,
  ensureDashboardTables,
  getBuiltInWidgetDefinitions,
  type WidgetDefinition,
} from "../dashboard.js";

describe("DashboardStore", () => {
  let db: Database.Database;
  let store: DashboardStore;

  beforeEach(() => {
    db = new Database(":memory:");
    ensureDashboardTables(db);
    store = new DashboardStore(db);
  });

  it("seeds a default dashboard profile from data-driven widget definitions", () => {
    const dashboards = store.list();

    expect(dashboards).toHaveLength(1);
    expect(dashboards[0].isDefault).toBe(true);
    expect(dashboards[0].widgets.map((widget) => widget.definitionId)).toContain("stats");
    expect(dashboards[0].layout.lg?.some((item) => item.i === "stats")).toBe(true);

    const catalog = store.listWidgetDefinitions();
    expect(catalog.map((definition) => definition.id)).toContain("dynamic-markdown");
    expect(getBuiltInWidgetDefinitions().every((definition) => definition.builtIn)).toBe(true);
  });

  it("creates profiles, switches the default profile, and manages profile widgets", () => {
    const originalDefault = store.list()[0];

    const security = store.create({
      name: "Security",
      description: "Security operations dashboard",
      isDefault: true,
      widgets: [],
      layout: { lg: [], md: [] },
    });

    expect(security.isDefault).toBe(true);
    expect(store.get(originalDefault.id)?.isDefault).toBe(false);

    const widget = store.addWidget(security.id, {
      definitionId: "dynamic-markdown",
      title: "Incident runbook",
      data: "## Escalation\nRotate tokens and notify operators.",
    });

    expect(widget.id).toBeTruthy();
    expect(widget.definitionId).toBe("dynamic-markdown");

    const updated = store.updateWidget(security.id, widget.id, {
      title: "Live incident runbook",
      config: { refreshInterval: 60 },
    });
    expect(updated?.title).toBe("Live incident runbook");
    expect(updated?.config.refreshInterval).toBe(60);

    expect(store.listWidgets(security.id)).toHaveLength(1);
    expect(store.deleteWidget(security.id, widget.id)).toBe(true);
    expect(store.listWidgets(security.id)).toHaveLength(0);
  });

  it("exports and imports custom widget definitions with dashboard profiles", () => {
    const customDefinition: WidgetDefinition = {
      id: "agent-error-chart",
      name: "Agent Error Chart",
      description: "Session-scoped error counts generated by the agent",
      category: "metrics",
      dataSource: { type: "static" },
      renderer: "chart",
      defaultSize: { w: 6, h: 5 },
      configSchema: {
        type: "object",
        properties: {
          label: { type: "string" },
        },
      },
      builtIn: false,
    };

    store.registerWidgetDefinition(customDefinition);
    const dashboard = store.create({
      name: "Generated",
      description: null,
      widgets: [],
      layout: { lg: [], md: [] },
    });
    store.addWidget(dashboard.id, {
      definitionId: customDefinition.id,
      title: "Today's errors",
      temporary: true,
      sessionId: "session-1",
      data: [
        { label: "API", value: 4 },
        { label: "Tools", value: 2 },
      ],
    });

    const exported = store.exportDashboard(dashboard.id);
    expect(exported.definitions).toHaveLength(1);
    expect(exported.definitions[0].id).toBe(customDefinition.id);

    const importedDb = new Database(":memory:");
    ensureDashboardTables(importedDb);
    const importedStore = new DashboardStore(importedDb);
    const imported = importedStore.importDashboard(exported, { name: "Imported generated" });

    expect(imported.name).toBe("Imported generated");
    expect(imported.widgets[0].definitionId).toBe(customDefinition.id);
    expect(importedStore.getWidgetDefinition(customDefinition.id)?.renderer).toBe("chart");
  });
});
